import type { Professor } from './types.js';

export const MOCK_PROFESSORS: Professor[] = [
  {
    id: '1',
    name: 'ดร.อิ่มจัง อาหารตามสั่ง',
    email: 'DrImjung.A@teacher.chula.ac.th',
    abbreviation: 'อ.อจ.',
    department: 'ภาควิชาบรรณารักษศาสตร์',
    location: 'ตึก BRK ห้อง 777',
    achievements: [
      'รางวัลอาจารย์ดีเด่น ปี 2563',
      'รางวัลงานวิจัยยอดเยี่ยม ปี 2562',
      'ใส่อะไรก็แล้วแต่ตามสบาย',
    ],
    qualifications: [
      'Ph.D. (TamsangFoodCooking) Chulalongkorn University, พ.ศ. 2551',
      'ใส่อะไรก็แล้วแต่ตามสบาย',
      'ใส่อะไรก็แล้วแต่ตามสบาย',
    ],
    courses: [
      '2267123 การลดต้นทุนสำหรับร้านตามสั่งตามหลักการแบบมนุษยศาสตร์',
      'ใส่อะไรก็แล้วแต่ตามสบาย',
      'ใส่อะไรก็แล้วแต่ตามสบาย',
    ],
  },
  {
    id: '2',
    name: 'ผศ.ดร.สมชาย ใจดี',
    email: 'Somchai.J@teacher.chula.ac.th',
    abbreviation: 'อ.สจ.',
    department: 'ภาควิชาภาษาไทย',
    location: 'ตึก TH ห้อง 201',
    achievements: ['รางวัลบทความวิจัยดีเด่น ปี 2564', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: [
      'Ph.D. (Thai Language) Chulalongkorn University, พ.ศ. 2555',
      'M.A. (Linguistics) ใส่อะไรก็แล้วแต่ตามสบาย',
    ],
    courses: ['2201101 ภาษาไทย 1', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '3',
    name: 'รศ.ดร.วิมลรัตน์ สุขสวัสดิ์',
    email: 'Wimonrat.S@teacher.chula.ac.th',
    abbreviation: 'อ.วร.',
    department: 'ภาควิชาภาษาอังกฤษ',
    location: 'ตึก EN ห้อง 301',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['Ph.D. (English Literature) Oxford University, พ.ศ. 2548'],
    courses: ['2203101 ภาษาอังกฤษเพื่อการสื่อสาร', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '4',
    name: 'อ.ดร.ประภาพร มีสุข',
    email: 'Prapaporn.M@teacher.chula.ac.th',
    abbreviation: 'อ.ปภ.',
    department: 'ภาควิชาประวัติศาสตร์',
    location: 'ตึก HI ห้อง 105',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['Ph.D. (History) Chulalongkorn University, พ.ศ. 2558'],
    courses: ['2205101 ประวัติศาสตร์ไทย', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '5',
    name: 'ศ.ดร.กิตติ วงศ์วิเชียร',
    email: 'Kitti.W@teacher.chula.ac.th',
    abbreviation: 'อ.กว.',
    department: 'ภาควิชาปรัชญา',
    location: 'ตึก PH ห้อง 402',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['Ph.D. (Philosophy) Harvard University, พ.ศ. 2540'],
    courses: ['2207101 ปรัชญาทั่วไป', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '6',
    name: 'อ.ดร.ณัฐฐา รุ่งเรือง',
    email: 'Nattha.R@teacher.chula.ac.th',
    abbreviation: 'อ.ณร.',
    department: 'ภาควิชาภาษาฝรั่งเศส',
    location: 'ตึก FR ห้อง 215',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['Ph.D. (French Literature) Paris University, พ.ศ. 2553'],
    courses: ['2209101 ภาษาฝรั่งเศสระดับต้น', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '7',
    name: 'ผศ.ดร.มนตรี ศิลปรัตน์',
    email: 'Montri.S@teacher.chula.ac.th',
    abbreviation: 'อ.มศ.',
    department: 'ภาควิชาศิลปการละคร',
    location: 'ตึก TH ห้อง 410',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['M.F.A. (Theatre Arts) Chulalongkorn University, พ.ศ. 2549'],
    courses: ['2211101 ศิลปการละครเบื้องต้น', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '8',
    name: 'รศ.ดร.เพ็ญพิมล จิตใจดี',
    email: 'Penpimol.J@teacher.chula.ac.th',
    abbreviation: 'อ.พจ.',
    department: 'ภาควิชาภูมิศาสตร์',
    location: 'ตึก GE ห้อง 101',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['Ph.D. (Geography) Chulalongkorn University, พ.ศ. 2550'],
    courses: ['2213101 ภูมิศาสตร์ทั่วไป', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '9',
    name: 'อ.ดร.สุวิชา นิลกร',
    email: 'Suwicha.N@teacher.chula.ac.th',
    abbreviation: 'อ.สน.',
    department: 'ภาควิชาบรรณารักษศาสตร์',
    location: 'ตึก BRK ห้อง 505',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['Ph.D. (Library Science) ใส่อะไรก็แล้วแต่ตามสบาย'],
    courses: ['2215101 การจัดการสารสนเทศ', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '10',
    name: 'ผศ.ดร.อนันต์ บุญสม',
    email: 'Anant.B@teacher.chula.ac.th',
    abbreviation: 'อ.อบ.',
    department: 'ภาควิชาภาษาเยอรมัน',
    location: 'ตึก GE ห้อง 210',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['Ph.D. (German Studies) Berlin University, พ.ศ. 2547'],
    courses: ['2217101 ภาษาเยอรมันระดับต้น', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '11',
    name: 'อ.ดร.ชนิดา มาลีวงศ์',
    email: 'Chanida.M@teacher.chula.ac.th',
    abbreviation: 'อ.ชม.',
    department: 'ภาควิชาภาษาสเปน',
    location: 'ตึก SP ห้อง 315',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['Ph.D. (Spanish Literature) ใส่อะไรก็แล้วแต่ตามสบาย'],
    courses: ['2219101 ภาษาสเปนระดับต้น', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '12',
    name: 'รศ.ดร.วัชรพล เกษมสุข',
    email: 'Watcharapol.K@teacher.chula.ac.th',
    abbreviation: 'อ.วก.',
    department: 'ภาควิชาจิตวิทยา',
    location: 'ตึก PS ห้อง 118',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['Ph.D. (Psychology) Chulalongkorn University, พ.ศ. 2552'],
    courses: ['2221101 จิตวิทยาทั่วไป', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
  {
    id: '13',
    name: 'ศ.ดร.สมพงษ์ ทองดี',
    email: 'Sompong.T@teacher.chula.ac.th',
    abbreviation: 'อ.สท.',
    department: 'ภาควิชาภาษาจีน',
    location: 'ตึก CH ห้อง 220',
    achievements: ['ใส่อะไรก็แล้วแต่ตามสบาย'],
    qualifications: ['Ph.D. (Chinese Literature) Beijing University, พ.ศ. 2545'],
    courses: ['2223101 ภาษาจีนระดับต้น', 'ใส่อะไรก็แล้วแต่ตามสบาย'],
  },
];

export const DEPARTMENT_OPTIONS = [
  'ทั้งหมด',
  'ภาควิชาบรรณารักษศาสตร์',
  'ภาควิชาภาษาไทย',
  'ภาควิชาภาษาอังกฤษ',
  'ภาควิชาประวัติศาสตร์',
  'ภาควิชาปรัชญา',
  'ภาควิชาภาษาฝรั่งเศส',
  'ภาควิชาศิลปการละคร',
  'ภาควิชาภูมิศาสตร์',
  'ภาควิชาภาษาเยอรมัน',
  'ภาควิชาภาษาสเปน',
  'ภาควิชาจิตวิทยา',
  'ภาควิชาภาษาจีน',
];

export const STATUS_OPTIONS = ['ทั้งหมด', 'ข้าราชการ', 'พนักงานมหาวิทยาลัย', 'พนักงานชั่วคราว'];

export const PROFESSORS_PER_PAGE = 13;
