import type { StudentProfile, YellowCardSubject, YellowCardCategory } from './types.js';

export const LOCAL_STORAGE_KEYS = {
  PDPA_AGREED: 'yellow_card_pdpa_agreed',
  PROFILE: 'yellow_card_profile',
  SUBJECTS: 'yellow_card_subjects',
  TRACKER_SUBJECTS: 'tracker_subjects',
} as const;

export const DEFAULT_PROFILE: StudentProfile = {
  name: 'นายบะหมี่  หมูย่างตรัง',
  studentId: '6741234567',
  major: 'สารสนเทศ',
  minor: 'ภาษาจีน',
  curriculum: 'ปี 2566',
  advisor: 'อาจารย์อิ่มจัง  อาหารตามสั่ง',
  address: 'ห้อง 148 ชั้น M1 อาคารมหาจักรีสิรินธร 254 ถนนพญาไท แขวงวังใหม่ เขตปทุมวัน กรุงเทพมหานคร 10330',
  phone: '081-234-5678',
};

export const CATEGORIES_CONFIG = [
  {
    category: 'credit_tracking.categories.basic' as YellowCardCategory,
    requiredCredits: 27,
    groups: [
      'credit_tracking.planner.groups.basic.g1',
      'credit_tracking.planner.groups.basic.g2',
      'credit_tracking.planner.groups.basic.g3',
      'credit_tracking.planner.groups.basic.g4',
      'credit_tracking.planner.groups.basic.g5',
    ],
  },
  {
    category: 'credit_tracking.categories.general' as YellowCardCategory,
    requiredCredits: 30,
    groups: [
      'yellow_card.groups.general.g1',
      'yellow_card.groups.general.g2',
      'yellow_card.groups.general.g3',
    ],
  },
  {
    category: 'credit_tracking.categories.free' as YellowCardCategory,
    requiredCredits: 6,
    groups: [
      'credit_tracking.planner.groups.free.g1',
    ],
  },
  {
    category: 'credit_tracking.categories.major' as YellowCardCategory,
    requiredCredits: 48,
    groups: [
      'credit_tracking.planner.groups.major.g1',
      'credit_tracking.planner.groups.major.g2',
      'credit_tracking.planner.groups.major.g3',
    ],
  },
  {
    category: 'credit_tracking.categories.minor' as YellowCardCategory,
    requiredCredits: 18,
    groups: [
      'credit_tracking.planner.groups.minor.g1',
      'credit_tracking.planner.groups.minor.g2',
    ],
  },
  {
    category: 'credit_tracking.categories.major' as YellowCardCategory,
    requiredCredits: 48,
    groups: [
      '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
      '2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต',
      '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
    ],
  },
  {
    category: 'credit_tracking.categories.minor' as YellowCardCategory,
    requiredCredits: 18,
    groups: [
      '1. วิชาบังคับ 12 หน่วยกิต',
      '2. วิชาเลือก 6 หน่วยกิต',
    ],
  },
];

export const INITIAL_SUBJECTS: YellowCardSubject[] = [
  // ==========================================
  // หมวดวิชาพื้นฐานอักษรศาสตร์
  // ==========================================
  // กลุ่มที่ 1
  {
    id: 'basic-g1-1',
    code: '0000000',
    nameKey: 'yellow_card.intro_thai_economy',
    semester: '2/57',
    credits: '3',
    grade: 'A',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g1',
  },
  {
    id: 'basic-g1-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g1',
  },
  {
    id: 'basic-g1-3',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g1',
  },
  {
    id: 'basic-g1-4',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g1',
  },
  {
    id: 'basic-g1-5',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g1',
  },
  {
    id: 'basic-g1-6',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g1',
  },

  // กลุ่มที่ 2
  {
    id: 'basic-g2-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g2',
  },
  {
    id: 'basic-g2-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g2',
  },
  {
    id: 'basic-g2-3',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g2',
  },
  {
    id: 'basic-g2-4',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g2',
  },

  // กลุ่มที่ 3
  {
    id: 'basic-g3-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g3',
  },
  {
    id: 'basic-g3-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g3',
  },
  {
    id: 'basic-g3-3',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g3',
  },
  {
    id: 'basic-g3-4',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g3',
  },

  // กลุ่มที่ 4
  {
    id: 'basic-g4-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g4',
  },
  {
    id: 'basic-g4-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g4',
  },
  {
    id: 'basic-g4-3',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g4',
  },
  {
    id: 'basic-g4-4',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g4',
  },

  // กลุ่มที่ 5
  {
    id: 'basic-g5-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g5',
  },
  {
    id: 'basic-g5-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g5',
  },
  {
    id: 'basic-g5-3',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g5',
  },
  {
    id: 'basic-g5-4',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.basic',
    group: 'credit_tracking.planner.groups.basic.g5',
  },

  // ==========================================
  // หมวดการศึกษาทั่วไป
  // ==========================================
  // กลุ่มที่ 1
  {
    id: 'gen-g1-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g1',
  },
  {
    id: 'gen-g1-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g1',
  },
  {
    id: 'gen-g1-3',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g1',
  },
  {
    id: 'gen-g1-4',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g1',
  },
  {
    id: 'gen-g1-5',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g1',
  },

  // กลุ่มที่ 2
  {
    id: 'gen-g2-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g2',
  },
  {
    id: 'gen-g2-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g2',
  },
  {
    id: 'gen-g2-3',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g2',
  },
  {
    id: 'gen-g2-4',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g2',
  },

  // กลุ่มที่ 3
  {
    id: 'gen-g3-1',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g3',
  },
  {
    id: 'gen-g3-2',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.general',
    group: 'yellow_card.groups.general.g3',
  },

  // ==========================================
  // หมวดวิชาเลือกเสรี
  // ==========================================
  {
    id: 'free-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.free',
    group: 'credit_tracking.planner.groups.free.g1',
  },
  {
    id: 'free-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.free',
    group: 'credit_tracking.planner.groups.free.g1',
  },

  // ==========================================
  // หมวดวิชาเอก
  // ==========================================
  // 1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต
  {
    id: 'major-comp-1',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g1',
  },
  {
    id: 'major-comp-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g1',
  },
  {
    id: 'major-comp-3',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g1',
  },
  {
    id: 'major-comp-4',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g1',
  },
  {
    id: 'major-comp-5',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g1',
  },
  {
    id: 'major-comp-6',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g1',
  },
  // 2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต
  {
    id: 'major-spec-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g2',
  },
  {
    id: 'major-spec-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g2',
  },
  {
    id: 'major-spec-3',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g2',
  },
  {
    id: 'major-spec-4',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g2',
  },
  // 3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต
  {
    id: 'major-exp-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g3',
  },
  {
    id: 'major-exp-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g3',
  },
  {
    id: 'major-exp-3',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g3',
  },
  {
    id: 'major-exp-4',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g3',
  },
  {
    id: 'major-exp-5',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g3',
  },
  {
    id: 'major-exp-6',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: 'credit_tracking.planner.groups.major.g3',
  },

  // ==========================================
  // หมวดวิชาโท
  // ==========================================
  // 1. วิชาบังคับ 12 หน่วยกิต
  {
    id: 'minor-comp-1',
    code: '0000000',
    nameKey: 'yellow_card.placeholder_subject',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: 'credit_tracking.planner.groups.minor.g1',
  },
  {
    id: 'minor-comp-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: 'credit_tracking.planner.groups.minor.g1',
  },
  {
    id: 'minor-comp-3',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: 'credit_tracking.planner.groups.minor.g1',
  },
  {
    id: 'minor-comp-4',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: 'credit_tracking.planner.groups.minor.g1',
  },
  // 2. วิชาเลือก 6 หน่วยกิต
  {
    id: 'minor-elect-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: 'credit_tracking.planner.groups.minor.g2',
  },
  {
    id: 'minor-elect-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: 'credit_tracking.planner.groups.minor.g2',
  },

  // ==========================================
  // หมวดวิชาเอก
  // ==========================================
  // 1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต
  {
    id: 'major-comp-1',
    code: '0000000',
    nameKey: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  {
    id: 'major-comp-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  {
    id: 'major-comp-3',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  {
    id: 'major-comp-4',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  {
    id: 'major-comp-5',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  {
    id: 'major-comp-6',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  // 2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต
  {
    id: 'major-spec-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต',
  },
  {
    id: 'major-spec-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต',
  },
  {
    id: 'major-spec-3',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต',
  },
  {
    id: 'major-spec-4',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต',
  },
  // 3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต
  {
    id: 'major-exp-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },
  {
    id: 'major-exp-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },
  {
    id: 'major-exp-3',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },
  {
    id: 'major-exp-4',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },
  {
    id: 'major-exp-5',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },
  {
    id: 'major-exp-6',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.major',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },

  // ==========================================
  // หมวดวิชาโท
  // ==========================================
  // 1. วิชาบังคับ 12 หน่วยกิต
  {
    id: 'minor-comp-1',
    code: '0000000',
    nameKey: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: '1. วิชาบังคับ 12 หน่วยกิต',
  },
  {
    id: 'minor-comp-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: '1. วิชาบังคับ 12 หน่วยกิต',
  },
  {
    id: 'minor-comp-3',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: '1. วิชาบังคับ 12 หน่วยกิต',
  },
  {
    id: 'minor-comp-4',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: '1. วิชาบังคับ 12 หน่วยกิต',
  },
  // 2. วิชาเลือก 6 หน่วยกิต
  {
    id: 'minor-elect-1',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: '2. วิชาเลือก 6 หน่วยกิต',
  },
  {
    id: 'minor-elect-2',
    code: '',
    nameKey: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'credit_tracking.categories.minor',
    group: '2. วิชาเลือก 6 หน่วยกิต',
  },
];
