import type { StudentProfile, YellowCardSubject, YellowCardCategory } from './types.js';

export const LOCAL_STORAGE_KEYS = {
  PDPA_AGREED: 'yellow_card_pdpa_agreed',
  PROFILE: 'yellow_card_profile',
  SUBJECTS: 'yellow_card_subjects',
  TRACKER_SUBJECTS: 'tracker_subjects',
} as const;

export const DEFAULT_PROFILE: StudentProfile = {
  name: 'นายบะหมี่  หมูย่างตรัง',
  studentId: '6741234567',
  major: 'สารสนเทศ',
  minor: 'ภาษาจีน',
  curriculum: 'ปี 2566',
  advisor: 'อาจารย์อิ่มจัง  อาหารตามสั่ง',
  address: 'ห้อง 148 ชั้น M1 อาคารมหาจักรีสิรินธร 254 ถนนพญาไท แขวงวังใหม่ เขตปทุมวัน กรุงเทพมหานคร 10330',
  phone: '081-234-5678',
};

export const CATEGORIES_CONFIG = [
  {
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์' as YellowCardCategory,
    requiredCredits: 27,
    groups: [
      'กลุ่มที่ 1 ทักษะการแสวงหาความรู้และการจัดการในโลกดิจิทัล',
      'กลุ่มที่ 2 วิจารณญาณเพื่อการดำรงตนในโลกร่วมสมัย',
      'กลุ่มที่ 3 การเรียนรู้และการตระหนักความเป็นไทย',
      'กลุ่มที่ 4 ความรู้เรื่องโลก/การเสริมสร้างความเป็นพลเมืองโลก',
      'กลุ่มที่ 5 ภูมิปัญญาและการแสดงออกของมนุษย์',
    ],
  },
  {
    category: 'หมวดการศึกษาทั่วไป' as YellowCardCategory,
    requiredCredits: 30,
    groups: [
      '1. วิชาการศึกษาทั่วไป 12 หน่วยกิต (จากกลุ่มวิชาสังคมศาสตร์ มนุษยศาสตร์ วิทยาศาสตร์และคณิตศาสตร์ และสหศาสตร์)',
      '2. วิชาการศึกษาทั่วไป กลุ่มภาษาต่างประเทศ 12 หน่วยกิต',
      '3. วิชาการศึกษาทั่วไปกลุ่มพิเศษ 6 หน่วยกิต',
    ],
  },
  {
    category: 'หมวดวิชาเลือกเสรี' as YellowCardCategory,
    requiredCredits: 6,
    groups: [
      'หมวดเลือกเสรี',
    ],
  },
  {
    category: 'หมวดวิชาเอก' as YellowCardCategory,
    requiredCredits: 48,
    groups: [
      '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
      '2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต',
      '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
    ],
  },
  {
    category: 'หมวดวิชาโท' as YellowCardCategory,
    requiredCredits: 18,
    groups: [
      '1. วิชาบังคับ 12 หน่วยกิต',
      '2. วิชาเลือก 6 หน่วยกิต',
    ],
  },
];

export const INITIAL_SUBJECTS: YellowCardSubject[] = [
  // ==========================================
  // หมวดวิชาพื้นฐานอักษรศาสตร์
  // ==========================================
  // กลุ่มที่ 1
  {
    id: 'basic-g1-1',
    code: '0000000',
    name: 'Introduction to Thai Economy',
    semester: '2/57',
    credits: '3',
    grade: 'A',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 1 ทักษะการแสวงหาความรู้และการจัดการในโลกดิจิทัล',
  },
  {
    id: 'basic-g1-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 1 ทักษะการแสวงหาความรู้และการจัดการในโลกดิจิทัล',
  },
  {
    id: 'basic-g1-3',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 1 ทักษะการแสวงหาความรู้และการจัดการในโลกดิจิทัล',
  },
  {
    id: 'basic-g1-4',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 1 ทักษะการแสวงหาความรู้และการจัดการในโลกดิจิทัล',
  },
  {
    id: 'basic-g1-5',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 1 ทักษะการแสวงหาความรู้และการจัดการในโลกดิจิทัล',
  },
  {
    id: 'basic-g1-6',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 1 ทักษะการแสวงหาความรู้และการจัดการในโลกดิจิทัล',
  },

  // กลุ่มที่ 2
  {
    id: 'basic-g2-1',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 2 วิจารณญาณเพื่อการดำรงตนในโลกร่วมสมัย',
  },
  {
    id: 'basic-g2-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 2 วิจารณญาณเพื่อการดำรงตนในโลกร่วมสมัย',
  },
  {
    id: 'basic-g2-3',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 2 วิจารณญาณเพื่อการดำรงตนในโลกร่วมสมัย',
  },
  {
    id: 'basic-g2-4',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 2 วิจารณญาณเพื่อการดำรงตนในโลกร่วมสมัย',
  },

  // กลุ่มที่ 3
  {
    id: 'basic-g3-1',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 3 การเรียนรู้และการตระหนักความเป็นไทย',
  },
  {
    id: 'basic-g3-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 3 การเรียนรู้และการตระหนักความเป็นไทย',
  },
  {
    id: 'basic-g3-3',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 3 การเรียนรู้และการตระหนักความเป็นไทย',
  },
  {
    id: 'basic-g3-4',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 3 การเรียนรู้และการตระหนักความเป็นไทย',
  },

  // กลุ่มที่ 4
  {
    id: 'basic-g4-1',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 4 ความรู้เรื่องโลก/การเสริมสร้างความเป็นพลเมืองโลก',
  },
  {
    id: 'basic-g4-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 4 ความรู้เรื่องโลก/การเสริมสร้างความเป็นพลเมืองโลก',
  },
  {
    id: 'basic-g4-3',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 4 ความรู้เรื่องโลก/การเสริมสร้างความเป็นพลเมืองโลก',
  },
  {
    id: 'basic-g4-4',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 4 ความรู้เรื่องโลก/การเสริมสร้างความเป็นพลเมืองโลก',
  },

  // กลุ่มที่ 5
  {
    id: 'basic-g5-1',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 5 ภูมิปัญญาและการแสดงออกของมนุษย์',
  },
  {
    id: 'basic-g5-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 5 ภูมิปัญญาและการแสดงออกของมนุษย์',
  },
  {
    id: 'basic-g5-3',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 5 ภูมิปัญญาและการแสดงออกของมนุษย์',
  },
  {
    id: 'basic-g5-4',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาพื้นฐานอักษรศาสตร์',
    group: 'กลุ่มที่ 5 ภูมิปัญญาและการแสดงออกของมนุษย์',
  },

  // ==========================================
  // หมวดการศึกษาทั่วไป
  // ==========================================
  // กลุ่มที่ 1
  {
    id: 'gen-g1-1',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '1. วิชาการศึกษาทั่วไป 12 หน่วยกิต (จากกลุ่มวิชาสังคมศาสตร์ มนุษยศาสตร์ วิทยาศาสตร์และคณิตศาสตร์ และสหศาสตร์)',
  },
  {
    id: 'gen-g1-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '1. วิชาการศึกษาทั่วไป 12 หน่วยกิต (จากกลุ่มวิชาสังคมศาสตร์ มนุษยศาสตร์ วิทยาศาสตร์และคณิตศาสตร์ และสหศาสตร์)',
  },
  {
    id: 'gen-g1-3',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '1. วิชาการศึกษาทั่วไป 12 หน่วยกิต (จากกลุ่มวิชาสังคมศาสตร์ มนุษยศาสตร์ วิทยาศาสตร์และคณิตศาสตร์ และสหศาสตร์)',
  },
  {
    id: 'gen-g1-4',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '1. วิชาการศึกษาทั่วไป 12 หน่วยกิต (จากกลุ่มวิชาสังคมศาสตร์ มนุษยศาสตร์ วิทยาศาสตร์และคณิตศาสตร์ และสหศาสตร์)',
  },
  {
    id: 'gen-g1-5',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '1. วิชาการศึกษาทั่วไป 12 หน่วยกิต (จากกลุ่มวิชาสังคมศาสตร์ มนุษยศาสตร์ วิทยาศาสตร์และคณิตศาสตร์ และสหศาสตร์)',
  },

  // กลุ่มที่ 2
  {
    id: 'gen-g2-1',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '2. วิชาการศึกษาทั่วไป กลุ่มภาษาต่างประเทศ 12 หน่วยกิต',
  },
  {
    id: 'gen-g2-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '2. วิชาการศึกษาทั่วไป กลุ่มภาษาต่างประเทศ 12 หน่วยกิต',
  },
  {
    id: 'gen-g2-3',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '2. วิชาการศึกษาทั่วไป กลุ่มภาษาต่างประเทศ 12 หน่วยกิต',
  },
  {
    id: 'gen-g2-4',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '2. วิชาการศึกษาทั่วไป กลุ่มภาษาต่างประเทศ 12 หน่วยกิต',
  },

  // กลุ่มที่ 3
  {
    id: 'gen-g3-1',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '3. วิชาการศึกษาทั่วไปกลุ่มพิเศษ 6 หน่วยกิต',
  },
  {
    id: 'gen-g3-2',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดการศึกษาทั่วไป',
    group: '3. วิชาการศึกษาทั่วไปกลุ่มพิเศษ 6 หน่วยกิต',
  },

  // ==========================================
  // หมวดวิชาเลือกเสรี
  // ==========================================
  {
    id: 'free-1',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเลือกเสรี',
    group: 'หมวดเลือกเสรี',
  },
  {
    id: 'free-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเลือกเสรี',
    group: 'หมวดเลือกเสรี',
  },

  // ==========================================
  // หมวดวิชาเอก
  // ==========================================
  // 1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต
  {
    id: 'major-comp-1',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  {
    id: 'major-comp-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  {
    id: 'major-comp-3',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  {
    id: 'major-comp-4',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  {
    id: 'major-comp-5',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  {
    id: 'major-comp-6',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '1. กลุ่มวิชาพื้นฐาน (บังคับ) 18 หน่วยกิต',
  },
  // 2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต
  {
    id: 'major-spec-1',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต',
  },
  {
    id: 'major-spec-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต',
  },
  {
    id: 'major-spec-3',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต',
  },
  {
    id: 'major-spec-4',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '2. กลุ่มวิชาข้อกำหนดเฉพาะ (วิชาเลือก) 12 หน่วยกิต',
  },
  // 3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต
  {
    id: 'major-exp-1',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },
  {
    id: 'major-exp-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },
  {
    id: 'major-exp-3',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },
  {
    id: 'major-exp-4',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },
  {
    id: 'major-exp-5',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },
  {
    id: 'major-exp-6',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาเอก',
    group: '3. กลุ่มวิชาเชี่ยวชาญ (วิชาเลือก) 18 หน่วยกิต',
  },

  // ==========================================
  // หมวดวิชาโท
  // ==========================================
  // 1. วิชาบังคับ 12 หน่วยกิต
  {
    id: 'minor-comp-1',
    code: '0000000',
    name: 'ชื่อวิชา',
    semester: '',
    credits: '3',
    grade: '',
    category: 'หมวดวิชาโท',
    group: '1. วิชาบังคับ 12 หน่วยกิต',
  },
  {
    id: 'minor-comp-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาโท',
    group: '1. วิชาบังคับ 12 หน่วยกิต',
  },
  {
    id: 'minor-comp-3',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาโท',
    group: '1. วิชาบังคับ 12 หน่วยกิต',
  },
  {
    id: 'minor-comp-4',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาโท',
    group: '1. วิชาบังคับ 12 หน่วยกิต',
  },
  // 2. วิชาเลือก 6 หน่วยกิต
  {
    id: 'minor-elect-1',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาโท',
    group: '2. วิชาเลือก 6 หน่วยกิต',
  },
  {
    id: 'minor-elect-2',
    code: '',
    name: '',
    semester: '',
    credits: '',
    grade: '',
    category: 'หมวดวิชาโท',
    group: '2. วิชาเลือก 6 หน่วยกิต',
  },
];
