import type { DocumentItem } from './types.js';

export const MOCK_DOCUMENTS: DocumentItem[] = [
  {
    id: '1',
    nameKey: 'documents.mock.doc1.name',
    detailsKey: 'documents.mock.doc1.details',
    categoryKey: 'documents.categories.internships',
    status: 'failed',
    downloadUrl: '#',
  },
  {
    id: '2',
    nameKey: 'documents.mock.doc2.name',
    detailsKey: 'documents.mock.doc2.details',
    categoryKey: 'documents.categories.internships',
    status: 'pending',
    downloadUrl: '#',
  },
  {
    id: '3',
    nameKey: 'documents.mock.doc3.name',
    detailsKey: 'documents.mock.doc3.details',
    categoryKey: 'documents.categories.internships',
    status: 'neutral',
    downloadUrl: '#',
  },
  {
    id: '4',
    nameKey: 'documents.mock.doc4.name',
    detailsKey: 'documents.mock.doc4.details',
    categoryKey: 'documents.categories.internships',
    status: 'neutral',
    downloadUrl: '#',
  },
  {
    id: '5',
    nameKey: 'documents.mock.doc5.name',
    detailsKey: 'documents.mock.doc5.details',
    categoryKey: 'documents.categories.courses',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '6',
    nameKey: 'documents.mock.doc6.name',
    detailsKey: 'documents.mock.doc6.details',
    categoryKey: 'documents.categories.scholarships',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '7',
    nameKey: 'documents.mock.doc7.name',
    detailsKey: 'documents.mock.doc7.details',
    categoryKey: 'documents.categories.internships',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '8',
    nameKey: 'documents.mock.doc8.name',
    detailsKey: 'documents.mock.doc8.details',
    categoryKey: 'documents.categories.kos',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '9',
    nameKey: 'documents.mock.doc9.name',
    detailsKey: 'documents.mock.doc9.details',
    categoryKey: 'documents.categories.others',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '10',
    nameKey: 'documents.mock.doc10.name',
    detailsKey: 'documents.mock.doc10.details',
    categoryKey: 'documents.categories.kos',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '11',
    nameKey: 'documents.mock.doc11.name',
    detailsKey: 'documents.mock.doc11.details',
    categoryKey: 'documents.categories.others',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '12',
    nameKey: 'documents.mock.doc12.name',
    detailsKey: 'documents.mock.doc12.details',
    categoryKey: 'documents.categories.courses',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '13',
    nameKey: 'documents.mock.doc13.name',
    detailsKey: 'documents.mock.doc13.details',
    categoryKey: 'documents.categories.kos',
    status: 'none',
    downloadUrl: '#',
  },
];

export const DOCUMENTS_PER_PAGE = 10;
