import type { DocumentItem } from './types.js';

export const MOCK_DOCUMENTS: DocumentItem[] = [
  {
    id: '1',
    name: 'ฟอร์มขอเอกสารขอความอนุเคราะห์ฝึกงาน.pdf',
    details: 'ข้อมูลเพิ่มเติม วันหมดอายุ/กำหนดส่ง',
    category: 'เกี่ยวกับฝึกงาน',
    status: 'failed',
    downloadUrl: '#',
  },
  {
    id: '2',
    name: 'ฟอร์มขอเอกสารขอความอนุเคราะห์ฝึกงาน.pdf',
    details: 'ข้อมูลเพิ่มเติม วันหมดอายุ/กำหนดส่ง',
    category: 'เกี่ยวกับฝึกงาน',
    status: 'pending',
    downloadUrl: '#',
  },
  {
    id: '3',
    name: 'ฟอร์มขอเอกสารขอความอนุเคราะห์ฝึกงาน.pdf',
    details: 'ข้อมูลเพิ่มเติม วันหมดอายุ/กำหนดส่ง',
    category: 'เกี่ยวกับฝึกงาน',
    status: 'neutral',
    downloadUrl: '#',
  },
  {
    id: '4',
    name: 'ฟอร์มขอเอกสารขอความอนุเคราะห์ฝึกงาน.pdf',
    details: 'ข้อมูลเพิ่มเติม วันหมดอายุ/กำหนดส่ง',
    category: 'เกี่ยวกับฝึกงาน',
    status: 'neutral',
    downloadUrl: '#',
  },
  {
    id: '5',
    name: 'แบบคำร้องขอลงทะเบียนเรียนข้ามมหาวิทยาลัย.pdf',
    details: 'ดาวน์โหลดแบบฟอร์มเพื่อส่งฝ่ายวิชาการ',
    category: 'เกี่ยวกับวิชาเรียน',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '6',
    name: 'ใบสมัครทุนการศึกษาคณะอักษรศาสตร์ ประจำปีการศึกษา 2569.pdf',
    details: 'กำหนดส่งเอกสารภายในวันที่ 30 มิถุนายน 2569',
    category: 'ทุนการศึกษา',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '7',
    name: 'หนังสือส่งตัวฝึกงานภายนอกคณะ.pdf',
    details: 'แนบใบตอบรับฝึกงานและส่งให้งานกิจการนิสิต',
    category: 'เกี่ยวกับฝึกงาน',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '8',
    name: 'ฟอร์มลงทะเบียนกิจกรรมสัมมนาวิชาการนิสิต.pdf',
    details: 'ส่งฟอร์มก่อนวันที่จัดสัมมนา 3 วัน',
    category: 'ฟอร์มต่าง ๆ ของกอศ.',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '9',
    name: 'แบบขออนุมัติจัดกิจกรรมโครงการส่งเสริมศิลปวัฒนธรรม.pdf',
    details: 'สำหรับชมรมในคณะอักษรศาสตร์',
    category: 'อื่น ๆ',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '10',
    name: 'ฟอร์มคำขอเบิกค่าใช้จ่ายกิจกรรมสโมสรนิสิต.pdf',
    details: 'แนบใบเสร็จรับเงินที่ถูกต้อง',
    category: 'ฟอร์มต่าง ๆ ของกอศ.',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '11',
    name: 'ใบรับรองการเข้าร่วมกิจกรรมนิสิตระดับคณะ.pdf',
    details: 'ใช้สำหรับประกอบการยื่นขอเกียรติบัตร',
    category: 'อื่น ๆ',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '12',
    name: 'คำร้องขอลาพักการเรียนชั่วคราว.pdf',
    details: 'ต้องได้รับการอนุมัติจากอาจารย์ที่ปรึกษา',
    category: 'เกี่ยวกับวิชาเรียน',
    status: 'none',
    downloadUrl: '#',
  },
  {
    id: '13',
    name: 'ฟอร์มขอเข้าใช้พื้นที่จัดกิจกรรมนิสิต.pdf',
    details: 'จองพื้นที่อย่างน้อย 7 วันทำการ',
    category: 'ฟอร์มต่าง ๆ ของกอศ.',
    status: 'none',
    downloadUrl: '#',
  },
];

export const DOCUMENTS_PER_PAGE = 10;
