import type { Subject, SubjectCategory } from './types.js';

export const MAJOR_OPTIONS = [
  'credit_tracking.profile.select_major',
  'credit_tracking.majors.thai',
  'credit_tracking.majors.english',
  'credit_tracking.majors.history',
  'credit_tracking.majors.geography',
  'credit_tracking.majors.information_studies',
  'credit_tracking.majors.philosophy',
  'credit_tracking.majors.dramatic_arts',
  'credit_tracking.majors.south_asian_languages',
  'credit_tracking.majors.chinese',
  'credit_tracking.majors.japanese',
  'credit_tracking.majors.korean',
  'credit_tracking.majors.french',
  'credit_tracking.majors.german',
  'credit_tracking.majors.spanish',
  'credit_tracking.majors.italian',
  'credit_tracking.majors.russian',
  'credit_tracking.majors.world_literature',
  'credit_tracking.majors.language_technology',
];

export const MINOR_OPTIONS = [
  'credit_tracking.profile.select_minor',
  'credit_tracking.minors.none',
  'credit_tracking.minors.vietnamese',
  'credit_tracking.minors.arabic',
  'credit_tracking.minors.portuguese',
  'credit_tracking.minors.linguistics',
  'credit_tracking.minors.comparative_literature',
  'credit_tracking.minors.khmer',
  'credit_tracking.minors.editorial_studies',
  'credit_tracking.minors.thai',
  'credit_tracking.minors.english',
  'credit_tracking.minors.history',
  'credit_tracking.minors.philosophy',
  'credit_tracking.minors.chinese',
  'credit_tracking.minors.japanese',
  'credit_tracking.minors.korean',
  'credit_tracking.minors.french',
  'credit_tracking.minors.german',
];

export const CURRICULUM_OPTIONS = [
  'credit_tracking.profile.select_curriculum',
  'credit_tracking.curriculums.cur2565',
  'credit_tracking.curriculums.cur2568',
];

export const MOCK_SUBJECTS: Subject[] = [
  // หมวดวิชาพื้นฐานอักษร (Required: 27 credits)
  {
    id: 'b1',
    code: '2201111',
    nameKey: 'credit_tracking.subjects.b1',
    credits: 3.00,
    category: 'credit_tracking.categories.basic',
    semester: 1,
    completed: true,
  },
  {
    id: 'b2',
    code: '2201112',
    nameKey: 'credit_tracking.subjects.b2',
    credits: 3.00,
    category: 'credit_tracking.categories.basic',
    semester: 1,
    completed: true,
  },
  {
    id: 'b3',
    code: '2201121',
    nameKey: 'credit_tracking.subjects.b3',
    credits: 3.00,
    category: 'credit_tracking.categories.basic',
    semester: 1,
    completed: true,
  },
  {
    id: 'b4',
    code: '2201122',
    nameKey: 'credit_tracking.subjects.b4',
    credits: 3.00,
    category: 'credit_tracking.categories.basic',
    semester: 2,
    completed: true,
  },
  {
    id: 'b5',
    code: '2201211',
    nameKey: 'credit_tracking.subjects.b5',
    credits: 3.00,
    category: 'credit_tracking.categories.basic',
    semester: 2,
    completed: true,
  },
  {
    id: 'b6',
    code: '2201221',
    nameKey: 'credit_tracking.subjects.b6',
    credits: 3.00,
    category: 'credit_tracking.categories.basic',
    semester: 3,
    completed: false,
  },
  {
    id: 'b7',
    code: '2201222',
    nameKey: 'credit_tracking.subjects.b7',
    credits: 3.00,
    category: 'credit_tracking.categories.basic',
    semester: 3,
    completed: false,
  },

  // หมวดการศึกษาทั่วไป (Required: 30 credits)
  {
    id: 'g1',
    code: '5500111',
    nameKey: 'credit_tracking.subjects.g1',
    credits: 3.00,
    category: 'credit_tracking.categories.general',
    semester: 1,
    completed: true,
  },
  {
    id: 'g2',
    code: '2200181',
    nameKey: 'credit_tracking.subjects.g2',
    credits: 3.00,
    category: 'credit_tracking.categories.general',
    semester: 2,
    completed: true,
  },
  {
    id: 'g3',
    code: '2200234',
    nameKey: 'credit_tracking.subjects.g3',
    credits: 3.00,
    category: 'credit_tracking.categories.general',
    semester: 3,
    completed: true,
  },
  {
    id: 'g4',
    code: '2200256',
    nameKey: 'credit_tracking.subjects.g4',
    credits: 3.00,
    category: 'credit_tracking.categories.general',
    semester: 4,
    completed: true,
  },

  // หมวดวิชาเอก (Required: 48 credits)
  {
    id: 'm1',
    code: '2202231',
    nameKey: 'credit_tracking.subjects.m1',
    credits: 3.00,
    category: 'credit_tracking.categories.major',
    semester: 3,
    completed: true,
  },
  {
    id: 'm2',
    code: '2202232',
    nameKey: 'credit_tracking.subjects.m2',
    credits: 3.00,
    category: 'credit_tracking.categories.major',
    semester: 4,
    completed: true,
  },
  {
    id: 'm3',
    code: '2202311',
    nameKey: 'credit_tracking.subjects.m3',
    credits: 3.00,
    category: 'credit_tracking.categories.major',
    semester: 5,
    completed: true,
  },
  {
    id: 'm4',
    code: '2202312',
    nameKey: 'credit_tracking.subjects.m4',
    credits: 3.00,
    category: 'credit_tracking.categories.major',
    semester: 5,
    completed: true,
  },
  {
    id: 'm5',
    code: '2202321',
    nameKey: 'credit_tracking.subjects.m5',
    credits: 3.00,
    category: 'credit_tracking.categories.major',
    semester: 6,
    completed: false,
  },
  {
    id: 'm6',
    code: '2202411',
    nameKey: 'credit_tracking.subjects.m6',
    credits: 3.00,
    category: 'credit_tracking.categories.major',
    semester: 7,
    completed: false,
  },

  // หมวดวิชาโท (Required: 18 credits)
  {
    id: 'mn1',
    code: '2209111',
    nameKey: 'credit_tracking.subjects.mn1',
    credits: 3.00,
    category: 'credit_tracking.categories.minor',
    semester: 4,
    completed: true,
  },
  {
    id: 'mn2',
    code: '2209211',
    nameKey: 'credit_tracking.subjects.mn2',
    credits: 3.00,
    category: 'credit_tracking.categories.minor',
    semester: 5,
    completed: true,
  },
  {
    id: 'mn3',
    code: '2209311',
    nameKey: 'credit_tracking.subjects.mn3',
    credits: 3.00,
    category: 'credit_tracking.categories.minor',
    semester: 6,
    completed: false,
  },

  // หมวดวิชาเลือกเสรี (Required: 6 credits)
  {
    id: 'f1',
    code: '2207111',
    nameKey: 'credit_tracking.subjects.f1',
    credits: 3.00,
    category: 'credit_tracking.categories.free',
    semester: 7,
    completed: true,
  },
  {
    id: 'f2',
    code: '2207222',
    nameKey: 'credit_tracking.subjects.f2',
    credits: 3.00,
    category: 'credit_tracking.categories.free',
    semester: 8,
    completed: false,
  },
];

export const CATEGORIES_CONFIG: { category: SubjectCategory; required: number }[] = [
  { category: 'credit_tracking.categories.basic', required: 27 },
  { category: 'credit_tracking.categories.general', required: 30 },
  { category: 'credit_tracking.categories.free', required: 6 },
  { category: 'credit_tracking.categories.major', required: 48 },
  { category: 'credit_tracking.categories.minor', required: 18 },
];
