import type { Subject, SubjectCategory } from './types.js';

export const MAJOR_OPTIONS = [
  'เลือกวิชาเอก',
  'ภาษาอังกฤษ',
  'ภาษาไทย',
  'ประวัติศาสตร์',
  'ปรัชญา',
  'ภูมิศาสตร์',
];

export const MINOR_OPTIONS = [
  'เลือกวิชาโท',
  'ภาษาอังกฤษ',
  'ภาษาไทย',
  'ประวัติศาสตร์',
  'ปรัชญา',
  'ไม่มีวิชาโท',
];

export const CURRICULUM_OPTIONS = [
  'เลือกหลักสูตร',
  'หลักสูตรอักษรศาสตร์บัณฑิต (ปรับปรุง 2565)',
  'หลักสูตรอักษรศาสตร์บัณฑิต (ปรับปรุง 2568)',
];

export const MOCK_SUBJECTS: Subject[] = [
  // หมวดวิชาพื้นฐานอักษร (Required: 27 credits)
  {
    id: 'b1',
    code: '2201111',
    nameTh: 'การใช้ภาษาไทย',
    nameEn: 'Use of the Thai Language',
    credits: 3.00,
    category: 'หมวดวิชาพื้นฐานอักษร',
    semester: 1,
    completed: true,
  },
  {
    id: 'b2',
    code: '2201112',
    nameTh: 'การอ่านวรรณคดีไทย',
    nameEn: 'Introduction to Thai Literature',
    credits: 3.00,
    category: 'หมวดวิชาพื้นฐานอักษร',
    semester: 1,
    completed: true,
  },
  {
    id: 'b3',
    code: '2201121',
    nameTh: 'ภาษาอังกฤษพื้นฐาน I',
    nameEn: 'Foundation English I',
    credits: 3.00,
    category: 'หมวดวิชาพื้นฐานอักษร',
    semester: 1,
    completed: true,
  },
  {
    id: 'b4',
    code: '2201122',
    nameTh: 'ภาษาอังกฤษพื้นฐาน II',
    nameEn: 'Foundation English II',
    credits: 3.00,
    category: 'หมวดวิชาพื้นฐานอักษร',
    semester: 2,
    completed: true,
  },
  {
    id: 'b5',
    code: '2201211',
    nameTh: 'การเขียนภาษาไทยเชิงสร้างสรรค์',
    nameEn: 'Creative Thai Writing',
    credits: 3.00,
    category: 'หมวดวิชาพื้นฐานอักษร',
    semester: 2,
    completed: true,
  },
  {
    id: 'b6',
    code: '2201221',
    nameTh: 'อารยธรรมตะวันตก',
    nameEn: 'Western Civilization',
    credits: 3.00,
    category: 'หมวดวิชาพื้นฐานอักษร',
    semester: 3,
    completed: false,
  },
  {
    id: 'b7',
    code: '2201222',
    nameTh: 'อารยธรรมตะวันออก',
    nameEn: 'Eastern Civilization',
    credits: 3.00,
    category: 'หมวดวิชาพื้นฐานอักษร',
    semester: 3,
    completed: false,
  },

  // หมวดการศึกษาทั่วไป (Required: 30 credits)
  {
    id: 'g1',
    code: '5500111',
    nameTh: 'การสื่อสารภาษาอังกฤษ',
    nameEn: 'Experiential English I',
    credits: 3.00,
    category: 'หมวดการศึกษาทั่วไป',
    semester: 1,
    completed: true,
  },
  {
    id: 'g2',
    code: '2200181',
    nameTh: 'การแสวงหาความรู้',
    nameEn: 'Inquiry and Discovery',
    credits: 3.00,
    category: 'หมวดการศึกษาทั่วไป',
    semester: 2,
    completed: true,
  },
  {
    id: 'g3',
    code: '2200234',
    nameTh: 'มนุษย์กับสังคม',
    nameEn: 'Man and Society',
    credits: 3.00,
    category: 'หมวดการศึกษาทั่วไป',
    semester: 3,
    completed: true,
  },
  {
    id: 'g4',
    code: '2200256',
    nameTh: 'วิทยาศาสตร์ในชีวิตประจำวัน',
    nameEn: 'Science in Everyday Life',
    credits: 3.00,
    category: 'หมวดการศึกษาทั่วไป',
    semester: 4,
    completed: true,
  },

  // หมวดวิชาเอก (Required: 48 credits)
  {
    id: 'm1',
    code: '2202231',
    nameTh: 'การออกเสียงภาษาอังกฤษ',
    nameEn: 'English Phonetics',
    credits: 3.00,
    category: 'หมวดวิชาเอก',
    semester: 3,
    completed: true,
  },
  {
    id: 'm2',
    code: '2202232',
    nameTh: 'ไวยากรณ์ภาษาอังกฤษวิเคราะห์',
    nameEn: 'Analytical English Grammar',
    credits: 3.00,
    category: 'หมวดวิชาเอก',
    semester: 4,
    completed: true,
  },
  {
    id: 'm3',
    code: '2202311',
    nameTh: 'การแปลภาษาอังกฤษขั้นต้น',
    nameEn: 'Introduction to English Translation',
    credits: 3.00,
    category: 'หมวดวิชาเอก',
    semester: 5,
    completed: true,
  },
  {
    id: 'm4',
    code: '2202312',
    nameTh: 'การอ่านตีความภาษาอังกฤษ',
    nameEn: 'Critical Reading in English',
    credits: 3.00,
    category: 'หมวดวิชาเอก',
    semester: 5,
    completed: true,
  },
  {
    id: 'm5',
    code: '2202321',
    nameTh: 'วรรณคดีอังกฤษสมัยพระนางเจ้าอลิซาเบธ',
    nameEn: 'Elizabethan Literature',
    credits: 3.00,
    category: 'หมวดวิชาเอก',
    semester: 6,
    completed: false,
  },
  {
    id: 'm6',
    code: '2202411',
    nameTh: 'การสัมมนาภาษาอังกฤษ',
    nameEn: 'Seminar in English Studies',
    credits: 3.00,
    category: 'หมวดวิชาเอก',
    semester: 7,
    completed: false,
  },

  // หมวดวิชาโท (Required: 18 credits)
  {
    id: 'mn1',
    code: '2209111',
    nameTh: 'วรรณกรรมศึกษาเบื้องต้น',
    nameEn: 'Introduction to Literary Studies',
    credits: 3.00,
    category: 'หมวดวิชาโท',
    semester: 4,
    completed: true,
  },
  {
    id: 'mn2',
    code: '2209211',
    nameTh: 'วรรณคดีเปรียบเทียบเบื้องต้น',
    nameEn: 'Introduction to Comparative Literature',
    credits: 3.00,
    category: 'หมวดวิชาโท',
    semester: 5,
    completed: true,
  },
  {
    id: 'mn3',
    code: '2209311',
    nameTh: 'ทฤษฎีวรรณคดีร่วมสมัย',
    nameEn: 'Contemporary Literary Theory',
    credits: 3.00,
    category: 'หมวดวิชาโท',
    semester: 6,
    completed: false,
  },

  // หมวดวิชาเลือกเสรี (Required: 6 credits)
  {
    id: 'f1',
    code: '2207111',
    nameTh: 'การเขียนบทภาพยนตร์ขั้นต้น',
    nameEn: 'Screenplay Writing I',
    credits: 3.00,
    category: 'หมวดวิชาเลือกเสรี',
    semester: 7,
    completed: true,
  },
  {
    id: 'f2',
    code: '2207222',
    nameTh: 'ดนตรีตะวันตกในชีวิตประจำวัน',
    nameEn: 'Western Music in Everyday Life',
    credits: 3.00,
    category: 'หมวดวิชาเลือกเสรี',
    semester: 8,
    completed: false,
  },
];

export const CATEGORIES_CONFIG: { category: SubjectCategory; required: number }[] = [
  { category: 'หมวดวิชาพื้นฐานอักษร', required: 27 },
  { category: 'หมวดการศึกษาทั่วไป', required: 30 },
  { category: 'หมวดวิชาเลือกเสรี', required: 6 },
  { category: 'หมวดวิชาเอก', required: 48 },
  { category: 'หมวดวิชาโท', required: 18 },
];
