export const PATHS = {
  ROOT: '/',
  ABOUT: '/about',
  CREDIT_TRACKING: '/credit-tracking',
  PROFESSORS: '/professors',
  STUDENT_SERVICES: '/student-services',
  STUDENT_SERVICES_2: '/student-service2',
  FORMS: '/forms',
  YELLOW_CARD: '/yellow-card',
  YELLOW_CARD_BACKOFFICE: '/yellow-card/backoffice',
  CURRICULUM: '/curriculum',
  INTERNSHIPS: '/internships',
  INTERNSHIPS_OPEN: '/internships/open',
  INTERNSHIPS_REVIEW: '/internships/review',
  ARTICLES: '/articles',
  CLUBS: '/clubs',
  HELP: '/help',
} as const;
